/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import io.warp10.plugins.macaroons.*;

public class MacaroonsPluginTest {
    @Test public void testSomeLibraryMethod() {
        MacaroonsPlugin plugin = new MacaroonsPlugin();
        assertTrue("TODO", false);
    }
}
